name: Push to S3

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_DEPLOY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_DEPLOY }}
          aws-region: us-east-1
      - name: Create env file
        run: |
          cat > env.yml << EOF
          ${{ secrets.ENV }}
          EOF
      - name: Sync files to S3 bucket
        run: |
          aws s3 sync build s3://tj-static-assets --delete
