name: Upload Website

on:
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Create env file
      run: |
          cat > env.yml << EOF
          ${{ secrets.ENV }}
          EOF
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_DEPLOY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_DEPLOY }}
